"""foundation: roles, bitfinex, nav, shares, config

Revision ID: 1e0e2ea97e2f
Revises: 3ebf341ea407
Create Date: 2026-05-22 16:58:24.726232

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1e0e2ea97e2f'
down_revision: str | None = '3ebf341ea407'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitfinex_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_raw_earnings', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('gross_nav', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('final_nav', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_aum_before', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_aum_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_shares_before', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_shares_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('admin_shares_issued', sa.Numeric(precision=20, scale=8), server_default='0', nullable=False),
    sa.Column('fee_threshold_apy_used', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fee_rate_used', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_nav_date'), 'daily_nav', ['date'], unique=True)
    op.create_table('funding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bitfinex_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_records_account_id'), 'funding_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_funding_records_date'), 'funding_records', ['date'], unique=False)
    op.create_table('product_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_config_key'), 'product_config', ['key'], unique=False)
    op.create_table('share_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('related_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_transactions_user_id'), 'share_transactions', ['user_id'], unique=False)
    op.create_table('user_share_snapshots',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('share_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###

    # Seed product_config initial values
    op.execute("""
        INSERT INTO product_config (key, value, effective_from)
        VALUES
            ('fee_threshold_apy', 0.04, '2026-01-01'),
            ('fee_rate', 0.5, '2026-01-01')
    """)


def downgrade() -> None:
    op.execute("DELETE FROM product_config WHERE key IN ('fee_threshold_apy', 'fee_rate')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('user_share_snapshots')
    op.drop_index(op.f('ix_share_transactions_user_id'), table_name='share_transactions')
    op.drop_table('share_transactions')
    op.drop_index(op.f('ix_product_config_key'), table_name='product_config')
    op.drop_table('product_config')
    op.drop_index(op.f('ix_funding_records_date'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_account_id'), table_name='funding_records')
    op.drop_table('funding_records')
    op.drop_index(op.f('ix_daily_nav_date'), table_name='daily_nav')
    op.drop_table('daily_nav')
    op.drop_table('bitfinex_accounts')
    # ### end Alembic commands ###
